### PR TITLE
Added Key Values link to Careers page

### PR DESCRIPTION
**Pull request by alexlsalt**
Screenshot (55)_LI

Links to https://www.keyvalues.com/orbit

### CODE REVIEW

**Comment by dzello** [comment]
[Add a link to our Key Values profile on https://orbit.love/careers](https://trello.com/c/J9yAzJKy/301-add-a-link-to-our-key-values-profile-on-https-orbitlove-careers)

**Comment by dzello** [comment]
@alexlsalt Nice work! I'd propose a small change to make the link a little bigger and leverage any recognition of the Key Values name. What do you think about this:

"We invite you to learn more about our values and our engineering culture on our [Key Values page](https://www.keyvalues.com/orbit)."

**Comment by alexlsalt** [comment]
@dzello Oh yeah, that's definitely looks better 👍

**Comment by alexlsalt** [comment]
Commenting about the Vercel error -- @phacks and I went through this and decided to push anyway, and it looks like it went successfully to production (https://orbit.love/careers). Will investigate more later.

**Comment by dzello** [comment]
@alexlsalt Thanks!

**Pull request merged**
